name: ci test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.8.0
          registry-url: https://registry.npmjs.org/
      - run: npm install

  node-tests:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.8.0
          registry-url: https://registry.npmjs.org/
      - run: npm run test:node

  browser-tests:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.8.0
          registry-url: https://registry.npmjs.org/
      - run: npm run test:browser