name: Docs Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tbdocs-reporter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      # https://cashapp.github.io/hermit/usage/ci/
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
        with:
          cache: "true"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build all workspace packages
        run: pnpm --recursive --stream build

      - name: TBDocs Reporter
        id: tbdocs-reporter-protocol
        uses: TBD54566975/tbdocs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report_changed_scope_only: false
          fail_on_warnings: false
          fail_on_error: false
          group_docs: true
          entry_points: |
            - file: packages/api/src/index.ts
              docsReporter: typedoc
              docsGenerator: typedoc-html
              readmeFile: packages/api/README.md
            - file: packages/crypto/src/index.ts
              docsReporter: typedoc
              docsGenerator: typedoc-html
              readmeFile: packages/crypto/README.md
            - file: packages/crypto-aws-kms/src/index.ts
              docsReporter: typedoc
              docsGenerator: typedoc-html
              readmeFile: packages/crypto-aws-kms/README.md
            - file: packages/dids/src/index.ts
              docsReporter: typedoc
              docsGenerator: typedoc-html
              readmeFile: packages/dids/README.md
            - file: packages/credentials/src/index.ts
              docsReporter: typedoc
              docsGenerator: typedoc-html
              readmeFile: packages/credentials/README.md

      - name: Save Artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 #v3.1.3
        if: always()
        with:
          name: tbdocs-reporter-output
          path: ./.tbdocs
