name: Docs Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tbdocs-reporter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@5ef044f9d09786428e6e895be6be17937becee3a #v4.0.0
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build all workspace packages
        run: npm run build

      - name: TBDocs Reporter
        id: tbdocs-reporter-protocol
        uses: TBD54566975/tbdocs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report_changed_scope_only: false
          fail_on_error: false
          group_docs: true
          entry_points: |
            - file: packages/api/src/index.ts
              docsGenerator: typedoc-html
              readmeFile: packages/api/README.md
              docsReporter: api-extractor
            - file: packages/crypto/src/index.ts
              docsGenerator: typedoc-html
              readmeFile: packages/crypto/README.md
              docsReporter: api-extractor
              docsReporterIgnore:
              - extractor:ae-missing-release-tag
              - docs:tsdoc-escape-greater-than
              - docs:tsdoc-at-sign-in-word
            - file: packages/crypto-aws-kms/src/index.ts
              docsGenerator: typedoc-html
              readmeFile: packages/crypto-aws-kms/README.md
              docsReporter: api-extractor
              docsReporterIgnore:
              - extractor:ae-missing-release-tag
              - docs:tsdoc-escape-greater-than
              - docs:tsdoc-at-sign-in-word

      - name: Save Artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 #v3.1.3
        if: always()
        with:
          name: tbdocs-reporter-output
          path: ./.tbdocs
