name: Create Dev Site Issue On Release

on:
  release:
    types: [created]

# Allow only one concurrent deployment,but do NOT cancel in-progress runs as
# we want to allow issue creation to complete.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DOCS_PAT }} # Assuming 'PAT' is your Personal Access Token stored as a secret
          script: |
            const issueTitle = `Web5 JS ${context.payload.release.tag_name} released`;
            const issueBody = `Please check the TBD Developer Site docs for compatibility with the release and update accordingly.\n\n[Click to view release notes](${context.payload.release.html_url})`;
            const labels = ['triage', 'BLOCKER'];
            github.rest.issues.create({
              owner: 'TBD54566975',
              repo: 'developer.tbd.website',
              title: issueTitle,
              body: issueBody,
              labels: labels
            });
