name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.8.0'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Publish packages
      run: |
        INITIAL_COMMIT=$(git rev-list --max-parents=0 HEAD)
        for dir in packages/*; do
          if [ -d "$dir" ] && git diff --name-only $INITIAL_COMMIT..HEAD -- "$dir/package.json"; then
            echo "Publishing $dir..."
            cd $dir
            echo "Checking npm authentication..."
            npm whoami
            npm publish
            cd ../..
          else
            echo "Skipping $dir..."
          fi
        done
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}